# Generated by Django 4.0.4 on 2022-04-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diamond',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('carat', models.FloatField(blank=True, null=True)),
                ('cut', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('clarity', models.CharField(blank=True, max_length=50, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('table', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
