# Generated by Django 4.0.3 on 2022-04-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
